server:
  port: 8085
spring:
  application:
    name: api-gateway
    
zuul:
  prefix: /api
  routes:
    company:
      path: /company/**
      service-id: COMPANY-SERVICE
    stock:
      path: /stock/**
      service-id: STOCK-SERVICE